import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'github-actions',
      label: 'Github Actions',
    },
    {
      type: 'category',
      label: 'Tailwindcss v4',
      collapsed: false,
      // link: {
      //   type: 'generated-index',
      //   title: 'Tailwindcss v4 Documentation',
      //   description: 'Browse all documentation related to Tailwind CSS v4',
      // },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tailwind-v4',
        },
      ],
    },
  ],

};

export default sidebars;
